getwd()
setwd("C:\\Users\\pcz\\OneDrive\\Desktop\\IT24102571_Lab8")
getwd()
data <- read.table("Exercise - Laptopsweights.txt", header = TRUE)
data <- as.numeric(unlist(data))
pop_mean <- mean(data, na.rm = TRUE)
pop_sd <- sd(data, na.rm = TRUE)
cat("Population Mean:", pop_mean, "\n")
cat("Population SD:", pop_sd, "\n")
set.seed(123)
sample_means <- c()
sample_sds <- c()
for(i in 1:25) {
  sample_data <- sample(data, size = 6, replace = TRUE)
  sample_means[i] <- mean(sample_data)
  sample_sds[i] <- sd(sample_data)
}
cat("Sample Means:", sample_means, "\n")
cat("SD of Sample Means:", sd(sample_means), "\n")
cat("Sample SDs:", sample_sds, "\n")